# generated by Git for Windows
echo '.bash_profile'
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# refer to symbo link node
NODE_HOME=/d/local/node

export PATH=$PATH:$NODE_HOME

export LANG=en_US.UTF-8
